Issue#45 refactoring script and test
hrsano645/covid19-gen-datajson-shizuokapref pull request #46
Opened 2021-02-25 13:05 UTC by hrsano645

## 👏 解決する issue / Resolved Issues
- close #45

## 📝 関連する issue / Related Issues
- #43 
- #42 

## ⛏ 変更内容 / Details of Changes

- 大規模なリファクタリングを行いました。
- オープンデータの入力とdata.jsonのそれぞれのデータの生成部分を関数にして分離しました
- それに伴い関数のテストを追加しました
- リファクタリングなので、生成結果は以前の状態と変わりません。
  - https://github.com/hrsano645/covid19-gen-datajson-shizuokapref/tree/dad95af99af58fd1d8d997e0b8daeb7129a93889 のcommitでデータの生成をテストして同様の結果となることを確認済みです。

## 📸 スクリーンショット / Screenshots

2021-02-28 06:34 UTC, aktnk commented on patients.py
> +def validate_opendata_dateformat(opendata_date_str: str) -> datetime:
機能的には検証する（validate）というよりは、文字列からdatetimeオブジェクトに変換している感じですね。
変換できなかった理由は、規定外の日付フォーマットだったわけですが。

例えば、create_datetimeなどの方が良いのかもしれません。

2021-02-28 06:34 UTC, aktnk commented on patients.py
> +        for n in range((end_datetime - start_datetime).days + 1)
元の実装で”+1”がありませんが、動作確認結果はOKとのことでした。
・元の実装には実はバグがあったということでしょうか？

もしかすると、https://github.com/hrsano645/covid19-gen-datajson-shizuokapref/issues/37
との関連があると思います。
data.jsonを生成したタイミングで、
１）patients.csvの最終データが同じ日付のとき、
２）patients.csvの最終データが以前の日付のとき、
で動作を確認すると良いと思います。

2021-02-28 06:34 UTC, aktnk commented on patients.py
> +def change_datetimestr_zeropadding(target_datetime: datetime) -> str:
関数名からは、ゼロ埋め（zeroppaing)するようにも読み取れるので、
remove_leading_zeroやsuppress_zero、change_zero_suppressin_formatなどに変更した方がよいと思いました。

2021-02-28 06:34 UTC, aktnk commented on patients.py
> +def gen_jsonformat_datetime(t_datetime: datetime) -> str:
機能的には、jsonフォーマットに変換するよ言うよりも、規定時刻（UTCの08:00:00.000）に合わせている感じですね。

元々08:00:00.000Zなのですが、UTCなので、ローカルタイムだと、8:00+9:00＝17:00にしているのはなぜでしょう？

2021-02-28 06:42 UTC, aktnk commented
差分では確認しにくかったので、動作フローを作成して関数名と動作の整合性を中心に確認してみました。
下記に作成した動作フロー図を掲載します。
- 全体動作フロー
![all](https://user-images.githubusercontent.com/13390370/109410080-fd092b00-79da-11eb-9d0a-efc47c16b3fd.png)
- gen_querents()の動作フロー
![gen_querents](https://user-images.githubusercontent.com/13390370/109410091-16aa7280-79db-11eb-9dff-cf89eab5de00.png)
- gen_patient()の動作フロー
![gen_patient](https://user-images.githubusercontent.com/13390370/109410100-29bd4280-79db-11eb-9834-fed7adf141df.png)
- gen_patient_summary()の動作フロー
![gen_patient_summary](https://user-images.githubusercontent.com/13390370/109410114-4f4a4c00-79db-11eb-8d77-addf0e21eac1.png)
- gen_inspections_summary()の動作フロー
![gen_inspections_summary](https://user-images.githubusercontent.com/13390370/109410122-62f5b280-79db-11eb-91db-0fe72ba69e7c.png)
- gen_main_summary()の動作フロー
![gen_main_summary](https://user-images.githubusercontent.com/13390370/109410129-73a62880-79db-11eb-94c2-22b339f3a762.png)

2021-02-28 06:43 UTC, aktnk requested changes
実装内容を確認しました。
いくつか気になった点をコメントしました。
コメントをご確認いただき、最終的に変更するかどうかの判断はお任せします。

2021-02-28 10:45 UTC, hrsano645 commented on patients.py
> +def validate_opendata_dateformat(opendata_date_str: str) -> datetime:
そうですね。実際の処理はそうなってるので、検証は検証で分けたほうがよさそうです。

2021-02-28 12:01 UTC, hrsano645 commented on patients.py
> +        for n in range((end_datetime - start_datetime).days + 1)
元の実装はendからstartの日付を引いているので、実質1日足らない状態でした。（1/31-1/1は30になってしまう話です）そのため+1しています。

それ自体は問題になりますが、見えてこなかった理由は、最近の要請患者数が連日件数が上がる為です。

patients_summaryは、グラフとして用意したい全体の日付 （全体）と、patients.csvから陽性者の日ごとの出現数（patients.csv）の生成をしています。

- 全体: 2020/01/22 ~ end_datetime（現在はpatients.csvの終端行の日付）
- patients.csv: 最初行の日付 ~ 終端行の日付

この処理部分は全体の日付の生成です。+1していない場合は冒頭に書いた通り1日少なくなってしまいます。終端行の日付-1の日付しか生成しないため、patients.csvの終端行日付から1日少なくずれてしまいます。

...といった事情で日付のラベルを作る際にこの処理にしています。ただ取り違えしやすいと思うので、書き方を工夫したかったのですが思いつかなかったです。

---

> data.jsonを生成したタイミングで、
> １）patients.csvの最終データが同じ日付のとき、
> ２）patients.csvの最終データが以前の日付のとき、
> で動作を確認すると良いと思います。

こちらはテスト入れたほうがいいと思うので追加しておきます。

2021-02-28 12:09 UTC, hrsano645 commented on patients.py
> +def change_datetimestr_zeropadding(target_datetime: datetime) -> str:
そうですね。changeだと除去ではないのでわかりづらいのはその通りだと思います。suppress_zeroがよさそうですね。

2021-02-28 13:00 UTC, hrsano645 commented on patients.py
> +def gen_jsonformat_datetime(t_datetime: datetime) -> str:
`08:00:00.000Z ` 添付の理由ですが、メトロ側がそうされているからと思われます。今のメトロ版 data.jsonも同様の表現です。

> 元々08:00:00.000Zなのですが、UTCなので、ローカルタイムだと、8:00+9:00＝17:00にしているのはなぜでしょう？
メトロ版のオープンデータ公開の時刻に合わせているからかもしれません。（確か会見が17時からだったと思います）

patientsのオープンデータAPI側を見てみると、公表日のフォーマットが同様ですが、時刻は`00:00:00.000Z`ですね。対策サイト側はこの部分を見ていないかもしれません。
https://portal.data.metro.tokyo.lg.jp/opendata-api/

2021-02-28 13:08 UTC, hrsano645 commented on patients.py
> +def gen_jsonformat_datetime(t_datetime: datetime) -> str:
この関数の意図としては、pythonのdatetimeをjsonに書き出すときの変換としていたので、中身含めてそのままで行こうと思っています。

2021-02-28 13:17 UTC, hrsano645 commented on patients.py
> +def validate_opendata_dateformat(opendata_date_str: str) -> datetime:
日付のバリデートについての必要性は、念のために必要だと考えていまして、どのタイミングでやろうか悩んでました。 -> https://github.com/hrsano645/covid19-gen-datajson-shizuokapref/issues/45#issuecomment-783746453

バリデーションしたときにエラーがあった場合は使えないデータとしてみるべきと考えていて、その流れで考えるとオープンデータを読み込むときにやるべきだと考えています。
（それで問題があったときにSlackに通知できたらいいなーと思ってますｗ

2021-02-28 13:22 UTC, hrsano645 commented
@aktnk 確認ありがとうございます。（フロー図すごいです。これって何か自動で生成させていますか？）
もう少し、処理の中身を手入れしたほうがいいところもあるのですが（例えばgen_関数でNoneを返すのに考慮してない 、関数でカプセル化した後での変数名の整理）、ひとまず目的は達成できたと思ってます。レビューの内容を修正したうえでmergeしようと思います。

修正については以下を行います。

- （日付のバリデーション処理と日付の生成を分ける -> ） **バリデーションするタイミングをオープンデータ生成時にして、問題があったときにエラーとして落とすようにする**
  - https://github.com/hrsano645/covid19-gen-datajson-shizuokapref/pull/46#discussion_r584242840
- `gen_datelist`関数にテストを追加する
  - https://github.com/hrsano645/covid19-gen-datajson-shizuokapref/pull/46#discussion_r584242849
- `change_datetimestr_zeropadding`関数の名前を `suppress_zero` に変更
  - https://github.com/hrsano645/covid19-gen-datajson-shizuokapref/pull/46#discussion_r584242864

2021-03-06 13:31 UTC, aktnk commented
> （フロー図すごいです。これって何か自動で生成させていますか？）

よく言えば、途中から自動生成です。
実装コードを読んで、PlantUML用のコードに自分が書いて、フロー図はPlantUMLに生成させています。
より詳しく説明すると、
１）PlantUMLサーバはDockerで立ち上げて、
２）VSCode＋PlantUML Pluginを使いPlantUMLサーバと連携させ、
３）自分が書いたUMLのアクティビティ図のコードをプレビューしたり、PNGファイルを生成させています。

2021-03-10 01:32 UTC, hrsano645 commented
@aktnk の指摘を反映しました。変更のコミットとコメントを残しておきます。

> * （日付のバリデーション処理と日付の生成を分ける -> ） **バリデーションするタイミングをオープンデータ生成時にして、問題があったときにエラーとして落とすようにする**
>   
>   * [#46 (comment)](https://github.com/hrsano645/covid19-gen-datajson-shizuokapref/pull/46#discussion_r584242840)

-> https://github.com/hrsano645/covid19-gen-datajson-shizuokapref/commit/7273e0581305506d83a7bdfb34f0f38dc8e87b17

- 日付のバリデート関数(isvalid_opendata_dateformat)とバリデート関数を各項目に実行する関数(validate_dataset関数）を追加しました。
- main関数でバリデーションの処理を追加して、バリデートしてエラーがある文字列をデータ名とセットに出力して例外終了するようにしました。
- data.jsonの各データの処理で入れてあったバリデート処理を外しました。

> * `gen_datelist`関数にテストを追加する
>   
>   * [#46 (comment)](https://github.com/hrsano645/covid19-gen-datajson-shizuokapref/pull/46#discussion_r584242849)

-> https://github.com/hrsano645/covid19-gen-datajson-shizuokapref/commit/7fc30970969df0d84065b5aa381a7dc0f1cdeefe

- gen_datelist関数にテストを追加しました。
- テストはstartとendの範囲とその範囲の日数を見ています。

> * `change_datetimestr_zeropadding`関数の名前を `suppress_zero` に変更
>   
>   * [#46 (comment)](https://github.com/hrsano645/covid19-gen-datajson-shizuokapref/pull/46#discussion_r584242864)

-> https://github.com/hrsano645/covid19-gen-datajson-shizuokapref/commit/c78abb8122d8d2bcea1ee631e9e4d4d27a0bde9f

2021-03-10 01:35 UTC, hrsano645 commented on patients.py
> +def validate_opendata_dateformat(opendata_date_str: str) -> datetime:
もともと関数名の指摘でしたが、処理の中身含めて整理しなおしました。

-> https://github.com/hrsano645/covid19-gen-datajson-shizuokapref/commit/7273e0581305506d83a7bdfb34f0f38dc8e87b17

- 日付のバリデート関数(isvalid_opendata_dateformat)とバリデート関数を各項目に実行する関数(validate_dataset関数）を追加しました。
- main関数でバリデーションの処理を追加して、バリデートしてエラーがある文字列をデータ名とセットに出力して例外終了するようにしました。
- data.jsonの各データの処理で入れてあったバリデート処理を外しました。

2021-03-10 01:37 UTC, hrsano645 commented on patients.py
> +        for n in range((end_datetime - start_datetime).days + 1)
こちらの変更は、+1がなぜ必要かの指摘で、もともとの実装だと想定した日付の日数が作れていないことがわかりました。

そのため（綺麗ではないのですが）+1を入れて数を合うようにしています。今後良い実装への変更も考えてテストを追加して日数計算が正しいかを検証できるようにしています。

> * `gen_datelist`関数にテストを追加する
>   
>   * [#46 (comment)](https://github.com/hrsano645/covid19-gen-datajson-shizuokapref/pull/46#discussion_r584242849)

-> https://github.com/hrsano645/covid19-gen-datajson-shizuokapref/commit/7fc30970969df0d84065b5aa381a7dc0f1cdeefe

- gen_datelist関数にテストを追加しました。
- テストはstartとendの範囲とその範囲の日数を見ています。

2021-03-10 01:37 UTC, hrsano645 commented on patients.py
> +def change_datetimestr_zeropadding(target_datetime: datetime) -> str:
関数名の変更への指摘を反映しました。

-> https://github.com/hrsano645/covid19-gen-datajson-shizuokapref/commit/c78abb8122d8d2bcea1ee631e9e4d4d27a0bde9f

2021-03-10 01:39 UTC, hrsano645 commented
レビューコメントにも返信で変更内容を追加しました。

2021-03-10 12:20 UTC, hrsano645 commented
バリデーションがどのように機能するか説明します。

テストデータを用意して実行した様子です。二つのファイルを一部の行だけ残して、日付をエラーが起こるようにわざと変更しています。

test_number.csv

```csv
実施_年月日,全国地方公共団体コード,都道府県名,"検査実施_人数
（保健所）","検査実施_人数
（医療機関等）",備考
～2020/4/26,220001,静岡県,"2,637",828,累計用
2020/4/27,220001,静岡県,39,63,
/2020/4/28,220001,静岡県,83,73,
2020/4/29,220001,静岡県,63,38,
~2020/4/30,220001,静岡県,38,32,
220/5/1,220001,静岡県,97,57,

```

call_center.csv
```csv
受付_年月日,全国地方公共団体コード,都道府県名,市区町村名,相談件数
2020/2/10,220001,静岡県,,0
/2020/2/11,220001,静岡県,,0
2020/2/12,220001,静岡県,,47
2020/2/13,220001,静岡県,,49
~2020/2/14,220001,静岡県,,74
2020/2/15,220001,静岡県,,61
2020/2/16,220001,静岡県,,28
220/2/17,220001,静岡県,,164
2020/2/18,220001,静岡県,,199

```


定義された日付のフォーマットではない場合は以下のように表示されます。

patients.pyの実行結果

```
Traceback (most recent call last):
  File "patients.py", line 621, in <module>
    main()
  File "patients.py", line 553, in main
    raise DateValidateError(error_msg)
__main__.DateValidateError: バリデーションの結果、処理出来ない行があります。処理を終了します。:
call_center: /2020/2/11
call_center: ~2020/2/14
call_center: 220/2/17
inspections_summary: /2020/4/28
inspections_summary: ~2020/4/30
inspections_summary: 220/5/1
```

2021-03-12 09:07 UTC, aktnk commented on patients.py
> +        for n in range((end_datetime - start_datetime).days + 1)
- 現時点のオープンデータでdata.jsonを生成してみました。
> 			{
> 				"日付": "2021-03-12T08:00:00.000Z",
> 				"小計": 17
> 			}
> 		]
既に、patients.csvには3/12のデータが掲載されており、正常に生成されていました。
- そこで故意にpatients.csvの3/12のデータを削除し、data.jsonを生成してみました。
> 			{
> 				"日付": "2021-03-11T08:00:00.000Z",
> 				"小計": 25
> 			}
> 		]
データがないのに、0で3/12のデータが生成されることはありませんでした。
⇒　問題ありません。

2021-03-12 09:14 UTC, aktnk approved these changes
@hrsano645 お疲れ様でした。
適切に修正されていることを確認しました。
また、data.jsonが問題なく生成されることも確認しました。

（参考）
patients.pyですが、各csvに対して似たような処理が繰り返される構造なので、
クラス化することで、凝集度を高めかつ、結合度を下げることができるかもしれないと思いました。

2021-03-12 10:44 UTC, hrsano645 commented
@aktnk ありがとうございます！mergeしますね。

> （参考）
> patients.pyですが、各csvに対して似たような処理が繰り返される構造なので、
> クラス化することで、凝集度を高めかつ、結合度を下げることができるかもしれないと思いました。

クラス化も考えてはいましたが、まずは現状の1ファイルのみでコードの状況整理をしたかったので、いきなりやらないでおきました。

このスクリプトもスクリプトといえる行数でもないので、モジュール分離をして各市町対応しやすい仕組みにできたらいいと思います。

2021-03-12 10:45 UTC, merged