Issue#10 add news json
hrsano645/covid19-gen-datajson-shizuokapref pull request #48
Opened 2021-03-27 12:23 UTC by hrsano645

## 👏 解決する issue / Resolved Issues
- close #10

## ⛏ 変更内容 / Details of Changes

- news.jsonの生成を行う`gen_newsjson.py`を用意
- 静岡県と富士市の生成に対応
  - bat.shの冒頭にある`LOCALNAME`に地域名を入れるとフィルターされます。デフォルトは静岡県に対応。
  - 今のところ市町は富士市のみしか想定していません。
- `patients.py`と環境を同一にするために、bat.shでPythonのvenvに対応しました。
  - crontabでの設定を想定してます。
  - テスト環境: Ubuntu18.04, Python 3.6.9

2021-04-21 14:07 UTC, hrsano645 commented on docker-compose.yml
> +      - ./patients.py:/code/patients.py:ro
volumesでは、ホストのカレンとディレクトリをボリューム設定して利用するのではなく、動作に必要なファイルのみをボリュームに設定しました。
またコンテナ側では読み取り専用にしています。

2021-04-21 14:08 UTC, hrsano645 reviewed
#47 から作業していた中で変更をした部分をあげておきます。

2021-04-24 22:22 UTC, aktnk commented on bat.sh
> +# 地域名を指定するときにはLOCALNAME変数に＊＊市と入力してください
現状、何も指定しなければ、静岡県のnews.jsonを生成し、
”富士市”を指定すれば、富士市のnews.jsonを生成し、
"三島市"を指定すると、何も生成されません。
（質問）
- 富士市以外もサポートしますか？
上記に合わせたコメントがされていると良いと思いました。

2021-04-24 22:24 UTC, aktnk commented on bat.sh
> +python gen_newsjson.py ${LOCALNAME}
生成に対応していないLOCALNAMEで実行された場合、
生成されない旨のメッセージが表示されると親切と思いました。
（関連）https://github.com/hrsano645/covid19-gen-datajson-shizuokapref/pull/48/files#r619717029

2021-04-24 22:44 UTC, aktnk commented on docker-compose.yml
> +      - ./patients.py:/code/patients.py:ro
（動作確認結果）
下記の指定になったため、生成されたnews.jsonがWindowsのHOST側からアクセスすることができませんでした。
- ro属性となったこと
- カレントディレクトリは3つのファイルしたバインドマウントしていないこと

（考察）
生成されたnews.jsonがWindowsホスト側のフォルダに残すため、
修正前のように
```
  volumes:
      - ./:/code
```
とするとか、生成するディレクトリを指定し、そのディレクトリをバインドマウントする等の対応が必要と思われます。

尚、現状でも
- dockerコンテナが残っている状態でdocker cpコマンドを実行するか、
- VSCodeでRemote Containerを使えば、コンテナ上のファイルをダウンロードできますが・・・

2021-04-24 22:53 UTC, aktnk commented on bat.sh
> +fi
このコードが入ったため、bat.shの実行時には、Dockerfileでインストールしたモジュール郡は使われなくなりましたね。
しかし、dockerコンテンにbashで入り、コマンドラインでpytest実行するには、Dockerfile側でインストールしたモジュールを使用しますので、両方必要でしょう・・・
もっとよい形がないでしょうか・・・

2021-04-24 22:54 UTC, aktnk commented on gen_newsjson.py
> +        LocalGenCls("静岡県", News(get_shizuoka_newslist)),
LOCALNAMEは”静岡県”でも良いのですね・・・

2021-04-24 22:56 UTC, aktnk commented on gen_newsjson.py
> +    for local_func in local_func_map:
静岡県、富士市以外が指定されたときのメッセージを入れたいです・・・

2021-04-24 22:59 UTC, aktnk requested changes
お待たせしました。
動作確認と合わせてコードも確認し、気になった点にコメントしました。
確認をお願いします。

2021-04-25 00:49 UTC, hrsano645 commented on bat.sh
> +# 地域名を指定するときにはLOCALNAME変数に＊＊市と入力してください
そうです。gen_newsjson.pyでは静岡県と富士市のみしか定義していないので、定義されていないと書いた方が良さそうですね。（もしくは全て出せるようにするのもありです。

2021-04-25 00:51 UTC, hrsano645 commented on bat.sh
> +python gen_newsjson.py ${LOCALNAME}
こちらもその通りですね。patients.pyとgen_newsjson.py側双方対応します。

2021-04-25 00:54 UTC, hrsano645 commented on gen_newsjson.py
> +        LocalGenCls("静岡県", News(get_shizuoka_newslist)),
そうですね。LOCALNAMEがない場合の処理を入れてるのですが、LOCALNAMEを静岡県とあらかじめ書いておけば良い（さらにLOCALNAMEがからかの処理も消せる）ので、bat.sh側に静岡県と記載するようにしてみます。

2021-04-25 00:55 UTC, hrsano645 commented on gen_newsjson.py
> +    for local_func in local_func_map:
メッセージ出すようにしてみます。

2021-04-25 01:02 UTC, hrsano645 commented on bat.sh
> +fi
このコードが入る理由は、本番環境向けになるのとDocker側ではどちらを使っても実質同じになるので、実質無視してもよいとおもってます。

そのほかの対応を考える

- Dockerfile側のRUN pip install... を除去する: docker側で環境整える時はbat.shを実行するか、手動でvenvを作成
- 本番環境でもDockerでの実行にする
- 本番環境のシステムでpipを走らせてしまう: あんまりおすすめできないですが、このプロジェクトのみで使われている場合なら選択肢としてはやっても問題にはならないかもしれません

2021-04-25 02:07 UTC, hrsano645 commented on docker-compose.yml
> +      - ./patients.py:/code/patients.py:ro
これも悩みました。Docker本来の使い方だと必要なファイルやディレクトリのみをボリューム設定する方が望ましいと思ってます。

ただ、今のところ困ることと言ったら、venvとキャッシュ周り(__pycache__とかpytestのキャッシュ)を入れてしまうことで、それを除外するボリューム設定をすればいいと思ってます。複数設定する必要になりますが、今の使い勝手の方が扱いやすいですよね。

#47 の修正前のような方法に戻した方がわかりやすいと思うので、除外ボリュームを増やして戻す対応をしてみます。

2021-04-25 02:33 UTC, hrsano645 commented
レビューありがとうございます。変更についてコメントしましたが、こちらにまとめると

- 検討中: bat.shのvenv生成については、Docker上で作成されても無視するか、他の対応を検討するか
- 対応する:
  - Dockerのボリュームは以前のものに戻す。venvとPython周りのキャッシュは除外する
  - bat.shのLOCALNAMEのデフォルトは"静岡県"を入れる
  - bat.shのLOCALNAMEのコメントには現在は静岡県と富士市のみ対応を記載する
  - patients.py, gen_newsjson.py側で対応しないLOCALNAMEが入った場合はメッセージを返す

2021-04-25 03:56 UTC, hrsano645 commented
LOCALNAME（地域名）の扱いですが、gen_newsjson.py側は定義した県と市町のみ対応なのでやりやすいです。

patients.pyは対応市町は逆に無い（別の県は無いのですが）ので、対応していないと出すべきかは悩みますね。

そのためpatients.pyには以下の対応にしてみます。

- フィルターして地域名と合致した件がある場合、その地域名でフィルターした陽性者属性一覧を出力する。
- フィルターして件数が0の場合は対応していないとメッセージを出して終了する。

また、patients.pyとgen_newsjson.pyは別々のプロセスで動かしてるので、それぞれの事情として扱ってみます。なのでpatients.pyで見つかった地域があってgen_newsjson.py側で見つからなかった場合は、data.jsonの生成のみ。news.jsonは生成されない状態になりますが、それが正しい挙動としてみます。

2021-04-25 06:18 UTC, hrsano645 commented on bat.sh
> +fi
（文章が途中のものだったので書き直しました💦

2021-04-25 06:41 UTC, hrsano645 commented on bat.sh
> +fi
一番いい方法だとやはりdockerで実行してしまう方法だと思ってます。どの環境でも同じように再現できますし。

2021-04-25 13:22 UTC, hrsano645 commented
レビュー出しておいて確認できてなかったのですが、一時的にオープンデータのCSVダウンロードを外した状態でした。

787b07b で修正済みです。🙏

---

オープンデータのCSVダウンロードを外していた理由ですが、2021/04/25の時点でCSVのパースができない状況だったので、手動でデータを処理した上でテストしてました。

最近何回かCSVを読み込めないことがあって、エラー周りを考慮した処理を用意する必要がありますね… 標準のCSVモジュールだと泥臭くチェックが必要で、pandasの方がデータの前処理を描きやすいのでPandasに置き換えてもいいかもしれません。

2021-04-26 13:33 UTC, aktnk approved these changes
動作確認しました。
Windows10ホスト側から生成されたcsvファイル、news.jsonファイルにアクセスできました。
LOCALNAMEのメッセージも表示されました。
OKです。

2021-04-26 23:31 UTC, hrsano645 commented
@aktnk ありがとうございます。mergeしますね🚀

2021-04-26 23:31 UTC, merged