Docker動作環境を用意する
hrsano645/covid19-gen-datajson-shizuokapref pull request #49
Opened 2021-04-12 12:05 UTC by hrsano645

## 👏 解決する issue / Resolved Issues
- close #47 

## 📝 関連する issue / Related Issues
- #10 

## ⛏ 変更内容 / Details of Changes

- 生成スクリプト開発用にdocker環境でも動作できるようにしました
- `docker-compose up --build` で実行します
- distフォルダが自動的に生成されて、その中にdata.jsonが作成されます
  - Linux環境の場合、ホストとコンテナのユーザーIDグループIDが違うため権限問題が発生しますがファイルのコピーをして利用はできます。
- テストの実行には対応していません

## 📸 スクリーンショット / Screenshots

Ubuntu 18.04での動作確認

![image](https://user-images.githubusercontent.com/23502/114390599-6f238100-9bd1-11eb-87d4-34463553f235.png)

Win10 + Docker Desktop での動作確認

![image](https://user-images.githubusercontent.com/23502/114390787-a8f48780-9bd1-11eb-8717-d7f4ee95430c.png)

2021-04-12 12:56 UTC, aktnk commented on Dockerfile
> +ENTRYPOINT ["bash", "./docker_bat.sh"]
ENTRYPOINTが指定されているので、docker_bat.shを実行することしかできません。

CMDに変更することで、Windowsでの開発作業でこのコンテナが使えるようにしませんか？

2021-04-12 13:01 UTC, aktnk commented on Dockerfile
> +COPY docker_bat.sh $PROJECT_ROOTDIR
docker専用にdocker_bat.shを作ると、bat.shの変更をした場合、docker_bat.shも変更しなければならなくなります。
docker_bat.shは作らずに、元のbat.shを、元のディレクトリ構造のまま使用できるようにしませんか？

2021-04-12 13:02 UTC, aktnk commented on docker_bat.sh
> +cp data.json ./dist/data.json
docker専用にdocker_bat.shを作ると、bat.shの変更をした場合、docker_bat.shも変更しなければならなくなります。
docker_bat.shは作らずに、元のbat.shを元のディレクトリ構造のまま使用できるようにしませんか？

2021-04-12 13:07 UTC, aktnk requested changes
docker環境でdata.jsonが生成できることは確認しました。
保守性・使い勝手を考慮し、変更をリクエストしました。

2021-04-13 05:36 UTC, hrsano645 reviewed
レビューありがとうございます！

doker_bat.shが新たにあると保守性が良くない話ですが、dockerに慣れていないところから始めたのもあって冗長なファイル構成にしてしまっています。

bat.shをdocker上で実行できる方が本来はよいはずなので、コメントの対応を進めてみます。

2021-04-13 05:36 UTC, hrsano645 commented on Dockerfile
> +COPY docker_bat.sh $PROJECT_ROOTDIR
> - docker専用にdocker_bat.shを作ると、bat.shの変更をした場合、docker_bat.shも変更しなければならなくなります。
docker_bat.shは作らずに、元のbat.shを、元のディレクトリ構造のまま使用できるようにしませんか

そうですね、できればbat.shで同じようにしたいと思ってます。

> - patients.pyの実行に、pythonモジュールのインストールは不要なんですね？

現時点ではそうなります。news.json生成の対応では、サードパーティのライブラリが必要で、pythonのvenv上で行うようなbat.shを作っていた( -> https://github.com/hrsano645/covid19-gen-datajson-shizuokapref/pull/48/files#diff-a8fdfba1fea6987e58250aec64eced080d7e677113f1fc389c437649f28bf8e8 )ので、これをdocker側に混ぜて使うことを想定していなくて別途docker用のbat.shを作りました。

ただ、docker上でもvenvを作成/実行可能ならbat.shのみで対応できるはずで、その検証はできていなかったので引き続き試してみます。（調べたらできそうな話もありました: https://pythonspeed.com/articles/activate-virtualenv-dockerfile/

2021-04-13 05:36 UTC, hrsano645 commented on Dockerfile
> +ENTRYPOINT ["bash", "./docker_bat.sh"]
CMDに変更しておきます！

2021-04-13 05:36 UTC, hrsano645 commented on docker_bat.sh
> +cp data.json ./dist/data.json
こちらのlineにリプライしました。
https://github.com/hrsano645/covid19-gen-datajson-shizuokapref/pull/49/files/c8bb340fdf83b4076a7122e6c59187b867c98e17#r611607055

2021-04-14 02:55 UTC, hrsano645 reviewed
@aktnk Docker向けのbat.shをなくして、bat.shで動作させるように対応しました。問題なさそうならそのままマージしますね。

2021-04-14 02:55 UTC, hrsano645 commented on Dockerfile
> +CMD ["bash", "./bat.sh"]
Docker用のbat.shを外してbat.shのみで動作可能にしました。
Docker上でvenvの動作も可能でしたので、この後ニュース生成用のPRにもDockerfileなど追加しますね。

2021-04-14 02:55 UTC, hrsano645 commented on bat.sh
> +LOCALNAME=""
LOCALNAME変数を追加して、地域ごとのデータ生成をしやすくしました。

2021-04-14 13:10 UTC, aktnk commented
動作させてみました。
・docker-compose up --buildでbat.shを実行することができました→〇
```
F:\Users\Akira\Documents\project\pr49_2>docker-compose up --build
Creating network "pr49_2_default" with the default driver
Building generator
failed to get console mode for stdout: The handle is invalid.
[+] Building 1.4s (9/9) FINISHED
 => [internal] load build definition from Dockerfile                       0.0s
 => => transferring dockerfile: 32B                                        0.0s
 => [internal] load .dockerignore                                          0.0s
 => => transferring context: 2B                                            0.0s
 => [internal] load metadata for docker.io/library/python:3.8              1.1s
 => [1/4] FROM docker.io/library/python:3.8@sha256:e31b6fa30c3204b2af4f08  0.0s
 => [internal] load build context                                          0.0s
 => => transferring context: 60B                                           0.0s
 => CACHED [2/4] WORKDIR /code                                             0.0s
 => CACHED [3/4] COPY patients.py /code                                    0.0s
 => CACHED [4/4] COPY bat.sh /code                                         0.0s
 => exporting to image                                                     0.0s
 => => exporting layers                                                    0.0s
 => => writing image sha256:b24b47c796e8a7b329f0686876a716e752f5b3724d6ff  0.0s
 => => naming to docker.io/library/pr49_2_generator                        0.0s
Successfully built b24b47c796e8a7b329f0686876a716e752f5b3724d6ff024e3c806b64c91b7a8
Creating covid19-data-generator-shizuokapref ... done
Attaching to covid19-data-generator-shizuokapref
covid19-data-generator-shizuokapref | ===[地域名: ]===
covid19-data-generator-shizuokapref | ===[generate data.json]===
covid19-data-generator-shizuokapref |   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
covid19-data-generator-shizuokapref |                                  Dload  Upload   Total   Spent    Left  Speed
100 12901  100 12901    0     0  56832      0 --:--:-- --:--:-- --:--:-- 56832
covid19-data-generator-shizuokapref |   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
covid19-data-generator-shizuokapref |                                  Dload  Upload   Total   Spent    Left  Speed
100  526k  100  526k    0     0  1571k      0 --:--:-- --:--:-- --:--:-- 1566k
covid19-data-generator-shizuokapref |   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
covid19-data-generator-shizuokapref |                                  Dload  Upload   Total   Spent    Left  Speed
100 11505  100 11505    0     0  63916      0 --:--:-- --:--:-- --:--:-- 63916
covid19-data-generator-shizuokapref |   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
covid19-data-generator-shizuokapref |                                  Dload  Upload   Total   Spent    Left  Speed
100   160  100   160    0     0    833      0 --:--:-- --:--:-- --:--:--   833
covid19-data-generator-shizuokapref exited with code 0
```
・そこで、patients.pyを修正しテストしようと思いました。
・コンテナの実行状態を確認すると、bat.shを実行しExitしています。

```
F:\Users\Akira\Documents\project\pr49_2>docker-compose ps
               Name                      Command      State    Ports
--------------------------------------------------------------------
covid19-data-generator-shizuokapref   bash ./bat.sh   Exit 0
```
・そのため、docker-compose runコマンドで再度コンテナを起動し、コンテナ内に入ります。
・テストを実行しようとtestディレクトリに移動しようとしましたが、コンテナ内にはtestディレクトリがありませんでした。→✕
```
F:\Users\Akira\Documents\project\pr49_2>docker-compose run generator /bin/bash
Creating pr49_2_generator_run ... done
root@86d9cb38600b:/code# ls
bat.sh  dist  patients.py
root@86d9cb38600b:/code#
```

2021-04-14 13:14 UTC, aktnk commented
動作させてみました。
（結果）
現状のコンテナを使い、WindowsPCから開発しようとすると、
bat.shの実行に必要なものしかないため、開発ができない状態です。
ここが改善されると、もっとよくなると思いました。
（詳細）
・docker-compose up --buildでbat.shを実行することができました→〇
```
F:\Users\Akira\Documents\project\pr49_2>docker-compose up --build
Creating network "pr49_2_default" with the default driver
Building generator
failed to get console mode for stdout: The handle is invalid.
[+] Building 1.4s (9/9) FINISHED
 => [internal] load build definition from Dockerfile                       0.0s
 => => transferring dockerfile: 32B                                        0.0s
 => [internal] load .dockerignore                                          0.0s
 => => transferring context: 2B                                            0.0s
 => [internal] load metadata for docker.io/library/python:3.8              1.1s
 => [1/4] FROM docker.io/library/python:3.8@sha256:e31b6fa30c3204b2af4f08  0.0s
 => [internal] load build context                                          0.0s
 => => transferring context: 60B                                           0.0s
 => CACHED [2/4] WORKDIR /code                                             0.0s
 => CACHED [3/4] COPY patients.py /code                                    0.0s
 => CACHED [4/4] COPY bat.sh /code                                         0.0s
 => exporting to image                                                     0.0s
 => => exporting layers                                                    0.0s
 => => writing image sha256:b24b47c796e8a7b329f0686876a716e752f5b3724d6ff  0.0s
 => => naming to docker.io/library/pr49_2_generator                        0.0s
Successfully built b24b47c796e8a7b329f0686876a716e752f5b3724d6ff024e3c806b64c91b7a8
Creating covid19-data-generator-shizuokapref ... done
Attaching to covid19-data-generator-shizuokapref
covid19-data-generator-shizuokapref | ===[地域名: ]===
covid19-data-generator-shizuokapref | ===[generate data.json]===
covid19-data-generator-shizuokapref |   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
covid19-data-generator-shizuokapref |                                  Dload  Upload   Total   Spent    Left  Speed
100 12901  100 12901    0     0  56832      0 --:--:-- --:--:-- --:--:-- 56832
covid19-data-generator-shizuokapref |   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
covid19-data-generator-shizuokapref |                                  Dload  Upload   Total   Spent    Left  Speed
100  526k  100  526k    0     0  1571k      0 --:--:-- --:--:-- --:--:-- 1566k
covid19-data-generator-shizuokapref |   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
covid19-data-generator-shizuokapref |                                  Dload  Upload   Total   Spent    Left  Speed
100 11505  100 11505    0     0  63916      0 --:--:-- --:--:-- --:--:-- 63916
covid19-data-generator-shizuokapref |   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
covid19-data-generator-shizuokapref |                                  Dload  Upload   Total   Spent    Left  Speed
100   160  100   160    0     0    833      0 --:--:-- --:--:-- --:--:--   833
covid19-data-generator-shizuokapref exited with code 0
```
・そこで、patients.pyを修正しテストしようと思いました。
・コンテナの実行状態を確認すると、bat.shを実行しExitしています。
```
F:\Users\Akira\Documents\project\pr49_2>docker-compose ps
               Name                      Command      State    Ports
--------------------------------------------------------------------
covid19-data-generator-shizuokapref   bash ./bat.sh   Exit 0
```
・そのため、docker-compose runコマンドで再度コンテナを起動し、コンテナ内に入ります。
・テストを実行しようとtestディレクトリに移動しようとしましたが、コンテナ内にはtestディレクトリがありませんでした。→✕
```
F:\Users\Akira\Documents\project\pr49_2>docker-compose run generator /bin/bash
Creating pr49_2_generator_run ... done
root@86d9cb38600b:/code# ls
bat.sh  dist  patients.py
root@86d9cb38600b:/code#
```

2021-04-15 00:10 UTC, hrsano645 commented
@aktnk  (docker)-compose自体まだよくわかっていないので、手取り足取りな形で申し訳ないです🙏

> ・そこで、patients.pyを修正しテストしようと思いました。
> ・コンテナの実行状態を確認すると、bat.shを実行しExitしています。

patients.pyを修正するためにコンテナに入るのはちょっと面倒ですよね…全体をdocker-composeのvolumesを使ってマウントして、ローカルでの変更をそのままコンテナ上で実行できるようにしてみます。

2021-04-15 04:47 UTC, hrsano645 commented
@aktnk 対応してみました。-> https://github.com/hrsano645/covid19-gen-datajson-shizuokapref/pull/49/commits/6a7451b7cf84d586356e16c8ae32879bbb69767e

venvをDockerfileで作成するようにして、スクリプトの実行やテストの実行も行えるようにしてみました。

また、docker-compose.yml を見直してローカルのファイルをそのままコンテナ側で参照するようにしました。ローカル側で変更してもbuildしなくてもよくなるはずです。

- 環境構築は `docker-compose build`
- スクリプトの実行は `docker-compose run generator` or `docker-compose up`
- テストの実行は `docker-compose run generator .venv/bin/pytest`
- コンテナ内で作業は `docker-compose run generator /bin/bash`

このDockerfile,docker-compose.yml はnews.json生成のbat.shでも動作できるようにもなってます。それについては #48 でまた言及します。

2021-04-18 12:13 UTC, aktnk commented on README.md
> +
ここまで進めていただいて、こんなこというのも・・・なんですが、
Win10 で docker を使用する場合も、下記に記載されたMac, Linux と極力同じようにオペレーションできるようにするのはどうでしょう？
```
$ python3 -m venv .venv
$ source .venv/bin/activate
$ pip install -U pip
$ pip install -r requirements.txt
```

2021-04-18 12:23 UTC, aktnk commented on README.md
> +
具体的な使い方イメージですが、

1. コンテナをバックグラウンドで実行
`> docker-compose up -d --build`
2. 実行中のコンテナでbashを起動しコンテナに入ります
`> docker-compose exec generator /bin/bash`
3. 後はMac,Linuxと同様にオペレーションします
```
$ python3 -m venv .venv
$ source .venv/bin/activate
$ pip install -U pip
$ pip install -r requirements.txt
```
4. テストを実行します
`$ pytest`
5. data.jsonを生成します
`$ bash bat.sh`
6. コンテナから抜け、コンテナを停止し、削除します。
```
$ exit
> docker-compose down
```

2021-04-19 00:29 UTC, hrsano645 commented on README.md
> +
なるほど。開発環境の作り方の話だと、すでにdockerfile上でvenvの作成/pipのパッケージインストールを行っているので

- docker-compose up -d --build: 開発環境のバックグラウンド起動-> buildオプションでvenvまで動作済み
- docker-compose exec generator /bin/bash: 開発環境へ入る

だけでコンテナに入って、あとはpytestもbat.sh実行も可能です。この流れをreadmeを変更すれば良さそうに思ってます。

2021-04-19 12:46 UTC, hrsano645 commented on README.md
> +
確認不足ですみませんが、今のDockerfileだとバックグラウンド起動ができない状態でした。DockerfileのCMDがbat.shだと、起動しただけで終了してしまうためと思います。

そのため、二つの変更をしておきます。

- Dockerfileの最終行にあるCMDをなくす: venvの環境準備までをDockerで行う。CMDを入れるとtty:trueにしても実行し続けられない。
- docker-composeにtty:trueオプションを入れる: デーモンがないコンテナを実行し続けるオプションを入れます。
  - 参考: [docker-composeで tty: true にしてデーモンがいないコンテナを動かし続ける - 今川館](http://imagawa.hatenadiary.jp/entry/2019/07/31/065830)

この二つの変更をすることで、`docker-compose up -d (--build)` で起動し続けて、`docker-compose exec generator /bin/bash` でコンテナ内に入れることを確認済みです。

また、venvの準備はすでにDockerfile上で行っているのでそのままにしようと思ってます。PATHを通しているためvenvの有効にしなくても良いため、コンテナに入ってそのままpytestなりbat.shを起動することも可能です。

2021-04-19 14:10 UTC, aktnk commented on README.md
> +
少々補足しながら、頭の中を整理してみます。
- 前回の私のコメント「Mac, Linux と極力同じようにオペレーションできるようにする」の裏には、
「Windows10用の特別な対応を極力増やさないようにしておく方が、後々の保守の手間を増やさないようにできる」のでは？と考えていました。

もし、Windows10とMac＆Linux環境で差異があってもよいとすれば、下記の疑問が生じました。
- 現状docker用の環境では、Mac＆Linuxと同じようにvenvを利用していますが、
実質、pythonモジュールのインストール場所として使っているだけです。
docker環境自体が使い捨ての環境なので、用事が済んだコンテナをすてることで、
ホスト側の環境を汚すことがありません。
とすると、venvを使わずとも、python:3.8環境に、`pip install -r requirements.txt`だけ実施すればよいのでは？
その方が、Dockerfile自体もシンプルになるし…
例えば下記のように…
```
FROM python:3.8

ENV PYTHONUNBUFFERED 1
ENV PROJECT_ROOTDIR /code
WORKDIR $PROJECT_ROOTDIR

COPY requirements.txt $PROJECT_ROOTDIR

RUN pip install -r requirements.txt
```

どう思いますか？

2021-04-20 00:46 UTC, hrsano645 commented on README.md
> +
このPRに対してはvenvは実質意味がないもので、意味なく入れてしまったのはまずかったと思ってます。

> * 現状docker用の環境では、Mac＆Linuxと同じようにvenvを利用していますが、
>   実質、pythonモジュールのインストール場所として使っているだけです。
>   docker環境自体が使い捨ての環境なので、用事が済んだコンテナをすてることで、
>   ホスト側の環境を汚すことがありません。
>   とすると、venvを使わずとも、python:3.8環境に、`pip install -r requirements.txt`だけ実施すればよいのでは？
>   その方が、Dockerfile自体もシンプルになる(例えば下記のように)と思います。
>   どう思いますか？

その通りだと思います。このPRではvenvを外したものを再度commitしますね

2021-04-20 00:50 UTC, hrsano645 commented on README.md
> +
venvを入れていた理由ですが（ちょっと長くてすみません）

並行してnews.jsonの生成スクリプトの動作方法を考えていたもので、あとで使うことになるので今のうちにいれておこうと思ったためです。

news.jsonのbat.shをdockerでも本番環境（さくらインターネットのサーバー環境）を動かすとき、本番環境ではvenvを使いたいと考えていました。そのためnews.json生成向けのbat.shはvenvを作る/有効にしたうえでの実行しています。

news.json向けのbat.sh: https://github.com/hrsano645/covid19-gen-datajson-shizuokapref/blob/210e858cf6e18efe97d4776facba621d8363de87/bat.sh

そもそもvenvを使う理由は、稼働しているサーバーのシステム側にpythonのパッケージを入れてしまうのは推奨されていない、仮に今の環境から別の環境に移ったときに環境構築の手間を省くためです。

（といってもシステム上にpython3, python3-venvは必須になります）

ただDocker環境だとvenvを作る必要性はないのですが、有効にしないとbat.shの動作ができないと考えていました。

この課題で悩んでいてdocker_bas.shを用意しましたが、開発上bat.shを別々にするのもよくないこともあって、bat.sh上ではvenvが存在する、なければ作るというコードを追加しています。

venvの利用については #48 が直接かかわるので続きはそちらで進めます。

2021-04-20 03:07 UTC, aktnk requested changes
Dockerfileの変更に伴い、docker-compose.ymlに不要な箇所があります。
ご確認お願いします。
なお、当方WSL2で動作させています。

2021-04-20 03:07 UTC, aktnk commented on docker-compose.yml
> +      - venv:/code/.venv
今回のDocketfileの変更により、venv のボリュームマウント含めて不要になると思います。

2021-04-20 03:07 UTC, aktnk commented on docker-compose.yml
> +  venv: {}
同上(ここも不要になると思います)

2021-04-20 09:39 UTC, hrsano645 commented on docker-compose.yml
> +  venv: {}
ありがとうございます。見落としてました。

2021-04-20 11:38 UTC, aktnk approved these changes
WSL2で動作確認できました。
ここまでいろいろとご対応いただき、ありがとうございました。

2021-04-21 00:24 UTC, hrsano645 commented
@aktnk こちらこそお付き合いいただいてありがたかったです！（めちゃくちゃ勉強になりました🙏

2021-04-21 00:25 UTC, merged