オープンデータにある空列や空行を除去する
hrsano645/covid19-gen-datajson-shizuokapref pull request #59
Opened 2021-06-04 00:39 UTC by hrsano645

## 👏 解決する issue / Resolved Issues
- close #53

## ⛏ 変更内容 / Details of Changes

- `patients.csv`に現れるときがある空列や空行を除去します

## 📸 スクリーンショット / Screenshots

空行の例

![image](https://user-images.githubusercontent.com/23502/116012274-99ab1a80-a664-11eb-820d-ba97982e783e.png)

空列は`patients.csv`にこういう行があるときに発生しがち

> 3895,3901,220001,静岡県,1,2021/1/18,,静岡市,高齢でない成人,男性,,軽症・中等症,発熱、咳,0,1
> 3896,3902,220001,静岡県,1,2021/1/18,,静岡市,40代,男性,会社員,軽症・中等症,倦怠感,0,1,,

この上と下は行数が違うので、Pythonで取り込むとこうなります。キーにNoneが入るような現象が起きてしまうので、これを取り除く処理を追加します。

> {'No': '3895', '例目': '3901', '全国地方公共団体コード': '220001', '都道府県名': '静岡県', '市区町村名': '1', '公表_年月日': '2021/1/18', '発症_年月日': '', '患者_居住地': '静岡市', '患者_年代': '高齢でない成人', '患者_性別': '男性', '患者_職業': '', '患者_状態': '軽症・中等症', '患者_症状': '発熱、咳', '患者_渡航歴の有無フラグ': '0', '患者_退院済フラグ': '1', '備考': None}
> {'No': '3896', '例目': '3902', '全国地方公共団体コード': '220001', '都道府県名': '静岡県', '市区町村名': '1', '公表_年月日': '2021/1/18', '発症_年月日': '', '患者_居住地': '静岡市', '患者_年代': '40代', '患者_性別': '男性', '患者_職業': '会社員', '患者_状態': '軽症・中等症', '患者_症状': '倦怠感', '患者_渡航歴の有無フラグ': '0', '患者_退院済フラグ': '1', '備考': '', None: ['']}

2021-06-05 12:40 UTC, hrsano645 commented
空列についての経緯も詳しく載せておきます。

先にまとめておくと空行を消す機能を追加しているが、オープンデータのCSVファイルにあるイレギュラーなカンマがあるおかげで空列と想定外の値が入ってしまって、空行の機能で例外が出てしまうので、先に空列を除去してます。

---

PRにあるこの部分の処理についてですが

```python
            # 未定義な列がある場合は除去
            for remove_key in ("", None):
                if remove_key in row.keys():
                    row.pop(remove_key)

            # 終端に空行がある場合は無視する
            if set(("", None)) == set(row.values()):
                continue
```

終端の空行は、set（集合型）を使って、空文字と列名が未定義の場合に現れるNoneのみが存在する行を無視しています。

スクリーンショットにあるカンマのみの部分をPythonで取り込んだ場合に以下のようになります。

> スクリーンショットにあるカンマが多い場合のCSV読み込み結果
> {'No': '', '例目': '', '全国地方公共団体コード': '', '都道府県名': '', '市区町村名': '', '公表_年月日': '', '発症_年月日': '', '患者_居住地': '', '患者_年代': '', '患者_性別': '', '患者_職業': '', '患者_状態': '', '患者_症状': '', '患者_渡航歴の有無フラグ': '', '患者_退院済フラグ': '', '備考': None}

> スクリーンショットにあるカンマが少ない場合のCSV読み込み結果
> {‘No’: ‘’, ‘例目‘: ‘’, ‘全国地方公共団体コード‘: ‘’, ‘都道府県名‘: ‘’, ‘市区町村名‘: ‘’, ‘公表_年月日‘: ‘’, ‘発症_年月日‘: None, ‘患者_居住地‘: None, ‘患者_年代‘: None, ‘患者_性別‘: None, ‘患者_職業‘: None, ‘患者_状態‘: None, ‘患者_症状‘: None, ‘患者_渡航歴の有無フラグ‘: None, ‘患者_退院済フラグ‘: None, ‘備考’: None}

無視する処理の部分では、set型を使っています。set型にシーケンシャルなオブジェクトを入れる（row.values()は値のみの一覧:シーケンシャルなオブジェクトを返します）と重複している値を取り除いてくれますが、上の二つの結果をset型に入れると空文字とNoneが戻ります。

```python
>>> csv_blank_row =  {'No': '', '例目': '', '全国地方公共団体コード': '', '都道府県名': '', '市区町村名': '', '公表_年月日': '', '発症_年月日': '', ' 患者_居住地': '', '患者_年代': '', '患者_性別': '', '患者_職業': '', '患者_状態': '', '患者_症状': '', '患者_渡航歴の有無フラグ': '', '患者_退院済フラグ': '', '備考': None}
>>> set(csv_blank_row.values())
{'', None}
```

そこで空列の行が関わるのですが、なぜか`patients.csv`にはカンマ数が定義されている列以上にある行がいくつかあり、Pythonで取り込んだ結果以下のようになります。

> {'No': '3896', '例目': '3902', '全国地方公共団体コード': '220001', '都道府県名': '静岡県', '市区町村名': '1', '公表_年月日': '2021/1/18', '発症_年月日': '', '患者_居住地': '静岡市', '患者_年代': '40代', '患者_性別': '男性', '患者_職業': '会社員', '患者_状態': '軽症・中等症', '患者_症状': '倦怠感', '患者_渡航歴の有無フラグ': '0', '患者_退院済フラグ': '1', '備考': '', None: ['']}

キー名がNoneになってるところは空のリストが入っています。通常だとみたことがないイレギュラーな値が入ってしまっています。

この状態でset型に値のシーケンシャルオブジェクトを渡すと以下のようなエラーが出ます。set型はリスト型を入れることができないのがエラーの原因です。

```
>>> csv_line =  {'No': '3896', '例目': '3902', '全国地方公共団体コード': '220001', '都道府県名': '静岡県', '市区町村名': '1', '公表_年月日': '2021/1/18', '発症_年月日': '', '患者_居住地': '静岡市', '患者_年代': '40代', '患者_性別': '男性', '患者_職業': '会社員', '患者_状態': '軽症・中等症', '患者_症状': '倦怠感', '患者_渡航歴の有無フラグ': '0', '患者_退院済フラグ': '1', '備考': '', None: ['']}
>>> csv_line
{'No': '3896', '例目': '3902', '全国地方公共団体コード': '220001', '都道府県名': '静岡県', '市区町村名': '1', '公表_年月日': '2021/1/18', '発症_年月日': '', '患者_居住地': '静岡市', '患者_年代': '40代', '患者_性別': '男性', '患者_職業': '会社員', '患者_状態': '軽症・中等症', '患者_症状': '倦怠感', '患者_渡航歴の有無フラグ': '0', '患者_退院済フラグ': '1', '備考': '', None: ['']}
>>> set(csv_line.values())
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: unhashable type: 'list'
```

空行を消す工程で、イレギュラーな空列が発生している状況があると実行できないので、先にイレギュラーな空列を消すようにしました。

2021-06-12 15:44 UTC, aktnk commented on patients.py
> +            # 未定義な列がある場合は除去
”未定義な列がある場合は除去”というと、上から下まで一列同じ行を除去するようにイメージします。
しかし、実際には1行取出し、その行内の””やNone（＝無効な要素）を取り除いてるだけです。
そこで、”行内の無効な要素を除去”等の方がコードとのズレがなく良いかと思いました。

2021-06-12 15:58 UTC, aktnk commented on patients.py
> +            # 終端に空行がある場合は無視する
”終端に空行がある場合は無視する”とありますが、
列名の数と、1行取り出した際の項目数がズレている場合、209行の条件が成り立つと考えられます。

そのため、”列名の数と実際の項目数が一致していない場合は無視する”とした方が、コメントとコードのズレがなく良いのではと思いました。

2021-06-12 16:00 UTC, aktnk commented on tests/test_perse.py
> +    assert 16 == len(load_matrix[0])
これは、テストが今まで間違っていたということでしょうか？

2021-06-12 16:02 UTC, aktnk requested changes
コメントの再考と、変更内容についての質問を行いました。
確認をお願いします。

2021-06-12 21:48 UTC, hrsano645 commented on tests/test_perse.py
> +    assert 16 == len(load_matrix[0])
そうでした。この修正を行う過程で見つけたものです。
テストを追加した当初は元のデータの列ヘッダにカンマが一つ終端に残っているので17行としていたのですが、データの仕様としては16行が正しいです。

仕様として確認するのか、データをそのまま見たときの行数を見るのかになると思いますが、parseとしているのでデータの仕様確認にしたほうがよさそうです。他のテストケースも同じように確認と修正かけたほうがよさそうに思ってます。

2021-06-12 22:24 UTC, hrsano645 reviewed
回答追加しました。コメントの部分は修正入れたものをcommitしますね。

2021-06-12 22:24 UTC, hrsano645 commented on patients.py
> +            # 終端に空行がある場合は無視する
> そのため、”列名の数と実際の項目数が一致していない場合は無視する”

```python
if set(("", None)) == set(row.values()):
    continue
```
（ここでいうrowはPythonの辞書(dict)形式で、dict.values() メソッドは辞書の値のみを取り出します）

ここのコードで行いたいことは

- 存在する項目がすべて空文字: 値が""の場合
- 列数が実際の項目より少ない（多くことも考えられます）: 値がNoneの時

この二つの条件が一致する行を除去するものでした。row.values()をset型に入れているので、""とNoneのみが残れば二つの条件に一致するはずです。

なので案をさらに拡張して、"存在する項目がすべて空文字で、列名の数と実際の項目数が一致していない場合は無視する" というコメントと処理の内容が伝わりやすそうです。

2021-06-12 22:24 UTC, hrsano645 commented on patients.py
> +            # 未定義な列がある場合は除去
> しかし、実際には1行取出し、その行内の””やNone（＝無効な要素）を取り除いてるだけです。
> そこで、”行内の無効な要素を除去”等の方がコードとのズレがなく良いかと思いました。

そうですね。ここで行いたいことは本来だとないはずの列名と項目を除去するのが目的なので、コメント変更します！

コードの詳細ですが、

```python
            for remove_key in ("", None):
                if remove_key in row.keys():
                    row.pop(remove_key)
```

この部分は、解説コメントに載せたこちらの問題に対応してます。

> そこで空列の行が関わるのですが、なぜか`patients.csv`にはカンマ数が定義されている列以上にある行がいくつかあり、Pythonで取り込んだ結果以下のようになります。
> 
> > {'No': '3896', '例目': '3902', '全国地方公共団体コード': '220001', '都道府県名': '静岡県', '市区町村名': '1', '公表_年月日': '2021/1/18', '発症_年月日': '', '患者_居住地': '静岡市', '患者_年代': '40代', '患者_性別': '男性', '患者_職業': '会社員', '患者_状態': '軽症・中等症', '患者_症状': '倦怠感', '患者_渡航歴の有無フラグ': '0', '患者_退院済フラグ': '1', '備考': '', None: ['']}
> 
> キー名がNoneになってるところは空のリストが入っています。通常だとみたことがないイレギュラーな値が入ってしまっています。
> 
> この状態でset型に値のシーケンシャルオブジェクトを渡すと以下のようなエラーが出ます。set型はリスト型を入れることができないのがエラーの原因です。
> 
> ```python
> >>> csv_line =  {'No': '3896', '例目': '3902', '全国地方公共団体コード': '220001', '都道府県名': '静岡県', '市区町村名': '1', '公表_年月日': '2021/1/18', '発症_年月日': '', '患者_居住地': '静岡市', '患者_年代': '40代', '患者_性別': '男性', '患者_職業': '会社員', '患者_状態': '軽症・中等症', '患者_症状': '倦怠感', '患者_渡航歴の有無フラグ': '0', '患者_退院済フラグ': '1', '備考': '', None: ['']}
> >>> csv_line
> {'No': '3896', '例目': '3902', '全国地方公共団体コード': '220001', '都道府県名': '静岡県', '市区町村名': '1', '公表_年月日': '2021/1/18', '発症_年月日': '', '患者_居住地': '静岡市', '患者_年代': '40代', '患者_性別': '男性', '患者_職業': '会社員', '患者_状態': '軽症・中等症', '患者_症状': '倦怠感', '患者_渡航歴の有無フラグ': '0', '患者_退院済フラグ': '1', '備考': '', None: ['']}
> >>> set(csv_line.values())
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
> TypeError: unhashable type: 'list'
> ```
> 
> 空行を消す工程で、イレギュラーな空列が発生している状況があると実行できないので、先にイレギュラーな空列を消すようにしました。

2021-06-12 23:46 UTC, aktnk approved these changes
毎度改善に取り組んでいただきありがとうございます。
コメント確認しました。
分かり易くなりました！

2021-06-13 07:21 UTC, hrsano645 commented
ありがとうございます！mergeします💪

2021-06-13 07:21 UTC, merged